[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"
  NEXT_TELEMETRY_DISABLED = "1"

# Redirects for SPA behavior
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Cache settings
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, must-revalidate"

# Enable pretty URLs by default
[[redirects]]
  from = "/blog/*"
  to = "/blog/:splat"
  status = 200

# Handle image paths
[[redirects]]
  from = "/images/*"
  to = "/images/:splat"
  status = 200
